---
# tasks file for nginx

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: copy config 
  copy:
    src: proxy.conf
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: start nginx
  service:
    name: nginx
    state: started